# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tolling_APP' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Tolling_APP

  pod 'Firebase/Core'
  pod 'Firebase/Database'

  target 'Tolling_APPTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Tolling_APP-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Tolling_APP-tvOS

  target 'Tolling_APP-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
